version: '3'
services:
  php-apache:
    container_name: php-apache
    # image: php:7.3-apache
    build: .
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80 
    depends_on:
      - db
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MY_DATABASE: db_test
      MY_USER: mysql
      MY_PASSWORD: 1234
    ports:
      - "3306:3306"

